### ISSUE TITLE
Install SMM-developed software for IU instance

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#1]
@bherr2 commented on [Wed Jan 10 2018](https://github.com/cns-iu/aisl/issues/23)

**Comment by bherr2** [comment]
Actually, I'll open another issue for the changes to be merged from SMM

**Comment by bryankennedy** [comment]
I have a diff of Trygve's code and will bring it into the xMacroscope system as my first step in the database sprint. We need to think about how to separate out the logic/state management system from the GraphQL layer on the server side.

**Comment by bryankennedy** [comment]
@bherr2 I'm wondering if we should close this issue or possibly update the description. I think some more specific issues describe some of the things that we're working on right now.

Or does this refer to installing the SMM client and server system on the computers at IU? Just trying to put a finer point on all the issues.

**Comment by bryankennedy** [comment]
@bherr2 I'm closing this for now, since I think it's old and covered by other work. But reopen if you disagree.
