### ISSUE TITLE
Upgrade packages to allow for Node 10 compatability

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#104]
There's some aspects of the serverGraphQL package that aren't working Node v10.

@bherr2 expressed a desire to get the system working with Node v10. I'm not sure yet, how easy it is to make the updates, but will look into it after getting the run logic system working.

**Comment by bherr2** [comment]
Ok, we're planning on upgrading our code to the latest Angular (6) and likely any upgrade issues involved.

**Comment by bryankennedy** [comment]
Does the Angular setup have any node version requirements?

**Comment by bherr2** [comment]
The minimum NodeJS version has also changed to 8.9+ (and NPM to 5.5+).

**Comment by bryankennedy** [comment]
OK, that's good. That'll be covered by the current LTS in case we run into any issues moving up to 10.

**Comment by bryankennedy** [comment]
We'll commit to getting this working for Phase 1. I think I just need to spend a little time figuring out why this isn't running in Node 10. There's no strong preference for backward compatibility.

**Comment by bherr2** [comment]
Agreed. For our MaV work we want to upgrade to the latest angular which works on older node, but is better to use node 10.

**Comment by azuldev1** [comment]
Dependancy Issue: bcrypt": "^1.0.3" used in the "server-graphql" package
<table>
<thead>
<tr>
<th>Node Version</th>
<th>Bcrypt Version</th>
</tr>
</thead>
<tbody>
<tr>
<td>0.4</td>
<td>&lt;= 0.4</td>
</tr>
<tr>
<td>0.6, 0.8, 0.10</td>
<td>&gt;= 0.5</td>
</tr>
<tr>
<td>0.11</td>
<td>&gt;= 0.8</td>
</tr>
<tr>
<td>4</td>
<td>&lt; 2.1</td>
</tr>
<tr>
<td>8</td>
<td>&gt;= 1.0.3</td>
</tr>
<tr>
<td>10</td>
<td>&gt;= 3</td>
</tr>
</tbody>
</table>

**Comment by bryankennedy** [comment]
OK, I've been banging my head against this for a while yesterday and today. 

Here's the process that brought me to my current impasse. @bherr2 it would be useful to get your angular advice here.

I am working on a branch off of develop. When I use node v9 I can get all of the packages to compile just fine.

When I switch to node 10 I get an error about upath being out of date. This is a sub-dependency of some old systems in the `server-graphql` package. To address this I:

- removed bcrypt modules
- upgraded sqlite

I only made these changes in the server-graphql package.

I then reinstalled all the node modules for the entire project with these commands in the root of the project:
```
rm yarn.lock; rm -rf node_modules; lerna clean -y;
lerna bootstrap
lerna link
```
Fortunately, this all installs correctly. I can run `yarn start` in `server-graphql` and `client-run`, however, I get an error when I try to run the `aisl` package.

```
/usr/local/src/xmacroscope/packages/aisl feature-phase-1-node-10*
❯ yarn start
yarn run v1.9.4
$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-10-16T15:18:50.024Z
Hash: 1fabed64530b161d9094
Time: 9163ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 858 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 327 kB [initial] [rendered]

ERROR in ../../node_modules/apollo-angular/types.d.ts(10,58): error TS2304: Cannot find name 'Exclude'.


webpack: Failed to compile.
```
When I search around about this issue it looks like a version issue with angular typescript and the apollo modules. I can try upgrading those, but I'm pretty out of my depth about the version concerns there.

Bruce, do you have any thoughts about what upgrades you would need to make there? Should I just proceed, assuming that you'll take over that work? I don't mean to create problem there. Let me know what you think.

**Comment by bryankennedy** [comment]
Here's the discussion I found about the apollo-angular package and the typescript version:
https://github.com/apollographql/apollo-angular/issues/770
Not sure if that's the core of the issue.

**Comment by bherr2** [comment]
Don't worry about the angular/mav side. We will be updating MaV to latest Angular when we start back up next week.

**Comment by bryankennedy** [comment]
OK, I'll leave this issue open until both of our packages fully work in Node 10. Everything is working in Node 10 on the client-run and server-graphql for me now. I'll ensure that this remains the case as we make any changes to other modules in the rest of the Phase 1 work.

**Comment by bryankennedy** [comment]
Moving to Phase 2 and CNS since the next steps here are angular work that'll happen in the next sprint.
