### ISSUE TITLE
Data loses color and shape once a row is selected

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#116]
So once a row is selected in the data table at the MAV, all points become gray circles. The selected one still pulses. This means visitors can apply shape and color coding to all points, including the last 4 runners.

**Comment by bherr2** [comment]
This will likely need to be handled in the ChangeTracker
https://github.com/cns-iu/xmacroscope/blob/develop/packages/client-mav/projects/xmacroscope-dvl-fw-plugin/src/lib/shared/change-tracker.ts#L77-L103
