### ISSUE TITLE
Update Field Encoding

### ISSUE THREAD

**Issue by GagsdName** [cns-iu/xmacroscope#135]
* [x] Restrict to the 5 fields specified
* [x] Change color coding to be monochromatic

**Comment by bherr2** [comment]
* number of siblings is not color coded and size coding doesn't work for siblings
* check color coding on geomap as well
* double check all 5 + 1 fields in both geomap and scatterplot to ensure coding is right
* reduce code duplication by moving default color and stroke offset into greyscale class
* "out of domain"/default color = rgb(255,255,255). stroke color = rgb(204, 204, 204)
* default offset = -51 for stroke

* do analogous for size coding that was done for color coding
