### ISSUE TITLE
Pick the shape and color of my persona

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#14]
As I user, I want to pick the shape and color of my persona when entering my data at the beginning of the experience - this will help me remember which one is me. #14

**Comment by bryankennedy** [comment]
@lecross defined 5 shapes that will be used initially.
 - square
 - cross
 - diamond
 - upward pointing triangle
 - star

and we'll start with 10 colors. @lecross can you define those and post their hex values here?

Bruce posted this data structure for the shapes and colors:
```
const RUNNER_SHAPES = [
	'square', 'cross', 'diamond', 'triangle-up', 'star'
];

const RUNNER_COLORS = [
	// fill in 10 friendly colors	
]; 
```

**Comment by bryankennedy** [comment]
Once we have that data @azuldev1 will work on building selection screen where visitors select a unique color and shape combination.

The initial selection screen will be "dumb." A visitor can select a color and shape combination and the next visitor who walks up to the signup screen can select the exact same selection.

After we get that working, we'll work on recording active color-shape combinations and locking those out.

**Comment by bryankennedy** [comment]
Right now this is still being generated randomly. I'm going to keep it that way for the first demo of the event. Once we get a more robust set of controls around the icon, I'll work on this.

**Comment by bryankennedy** [comment]
@bherr2 I think this will require an effort from both of our teams. Should we commit to making this work in Phase 1?

We'll need to track which shapes and colors are currently in use so that if a shape/color combo is on the MAV display still, it can't be selected on the start line screen.

**Comment by bherr2** [comment]
I think we should. MaV display is always last 50 so should be fairly easy to keep track of.

**Comment by bryankennedy** [comment]
The color and shape selection is working and getting saved to the db now.
