### ISSUE TITLE
Server side: runSelected subscription returns null

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#149]
When I subscribe to runSelected, the response I get back is null. You can try in graphiql to reproduce.

```
subscription runSelected {
  runSelected {
    type
    timestamp
    avatar {
      id
      name
      runMillis
    }
  }
}
```

Returns:
```
{
  "runSelected": null
}
```

**Comment by bryankennedy** [comment]
Strange, I do see the published message getting sent on the server side. I added some messaging on the server to confirm that this is firing: 49ee172

I'll continue looking to see where this is not coming across.

**Comment by bryankennedy** [comment]
Ha, we saw it almost at the same time, just pushed a fix that changes the typo. Thanks for helping me see that.
