### ISSUE TITLE
Server side: Add height and siblings to raceCompleted message / Persona

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#150]
raceCompleted needs to add height and siblings. Below is the subscription used in AISL with the two missing fields commented out. 

```
subscription raceCompleted {
    raceCompleted {
      type
      timestamp
      avatar {
        id
        name
        runMillis
      }
      results {
        lane
        persona {
          id
          name
          icon
          color
          gender
          age_group
          handedness
          # height
          # siblings
          zipcode
          state
          latitude
          longitude
        }
        started
        falseStart
        timeMillis
      }
    }
  }
```

**Comment by bryankennedy** [comment]
What unit are you using for height?
Do you have a max number of siblings that you're filtering out?

**Comment by bherr2** [comment]
See: https://github.com/cns-iu/xmacroscope/blob/develop/packages/aisl-api/src/mocks/persona.mock.ts#L50-L51

**Comment by bherr2** [comment]
Height in Inches (int): 36-96 
# siblings (int): 0-12

**Comment by bherr2** [comment]
Something still doesn't seem right. When viewing the data in graphiql it shows height and num siblings as null... Also, it seems like the shape/color is always the same...

**Comment by bryankennedy** [comment]
There's an issue with the random data that I'm starting on that should fix the shape and color staying the same I think. #155 

I'm looking into the null data.

**Comment by bryankennedy** [comment]
Just pushed another pull request that should fix this. On my setup I am seeing the height and siblings fields come across with new random data both in graphiql and in the MAV messages page.

**Comment by bherr2** [comment]
Looks good!
