### ISSUE TITLE
Server side: runs query not sufficient to recreate race complete messages

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#151]
The current runs query does not return enough information to recreate run completed messages. We need a query that returns exactly the same data as the raceCompleted subscription with an option to select the last X race completed messages to pull.

We will use this to query the last 50 race completed messages and then simultaneously created a subscription to raceCompleted.

**Comment by bryankennedy** [comment]
Understood. I can wire that up.

**Comment by bryankennedy** [comment]
All the data is showing up in the GraphQL query. Bruce could you confirm that this is working from your end?

https://d.pr/i/yTgw8G

Please note that some of the schema is a bit different to match the database fields. If you can work around the names for now we can get all our naming conventions sorted out later in a refactor.

**Comment by bherr2** [comment]
Its not ideal with the divergent schemas, but we can deal with it for now. I hooked the query up to the client and it appears to work good. I did make one change to the mock data generator so that it would match the mock data values we are expecting. 

Otherwise, we were able to demonstrate a full actual exhibit run!

**Comment by bryankennedy** [comment]
Glad this is working for the demonstration.

Yes, after I'm back I'd like to reserve some time to do some name cleanup so that our two systems are speaking the same language. Now that we're establishing the database tables and a more developed schema it would be good to prune the schema down to only used fields and common names.
