### ISSUE TITLE
client-run should listen for keys pressed by sensors

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#152]
At least implementing the end sensor. I guess start sensor is more for false start tripping, which would be nice to have.

**Comment by bryankennedy** [comment]
Yes, I'm working on implementing a new screen that will handle the keypresses from the designed start screen. The current start line screen is a dev setup.

**Comment by bryankennedy** [comment]
This should be working now. Close if you don't see any issues.

**Comment by bherr2** [comment]
Works great! Thanks
