### ISSUE TITLE
Upgrade to use latest Angular and DVL-FW

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#170]
* [ ] Update AISL/Make-A-Vis to Angular 7
* [ ] Use dvl-fw from new Make-A-Vis project

**Comment by bherr2** [comment]
It may make most sense to start a new angular cli project and copy over things as needed. This will live in the lerna workspace, so there may be some issues we haven't encountered yet with Angular 6+. 

Instead of packages/aisl, let's name it package/client-mav

**Comment by bryankennedy** [comment]
I like that name.
