### ISSUE TITLE
Put Persona on End-line Screen

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#171]
After a race finishes, draw the Persona Icon next to the runner's time. Also, make big time the same as the slowest runner's time.

**Comment by bryankennedy** [comment]
Manuel and I clarified this point. Right now the End Line screen is on the MAV application. So Bruce's group will work on this one.

FYI, in the SMM setup this screen is controlled by the server program. We might look at where this gets developed out in the future, as we add features here.

**Comment by bherr2** [comment]
Our endline screen just listens for the three graphql events and reacts accordingly. We had talked about putting some visualization elements in there at some point, which is part of why we have handled it thus far.
