### ISSUE TITLE
Change run time cutoff

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#172]
If a run is triggered and not finished it goes on forever. Change the timeout for this to something reasonable like 10-15 seconds.

**Comment by bryankennedy** [comment]
@bherr2 do you want me to make this change for the default location? This is currently a setting that each location can set to a custom value. Just making sure I understand.

**Comment by bryankennedy** [comment]
I can't reproduce this one right now. The timeout at the end of the race is working for me in the `feature-phase-1` branch right now. I'll move this back to the backlog for now, but let me know if I'm missing something here.

**Comment by bryankennedy** [comment]
Moving down to the bottom in Phase 2 until I can get more details.

**Comment by bherr2** [comment]
@KalaRaja use the config object on the xmacroscope data service. Can't remember which variable to use but should be one of:
      preRunDelay
      postRunDelay
      startLineTimeout
      runTimeout
      attractDelay

**Comment by bherr2** [comment]
I realize that may not be clear. Basically you need a timeout when the timer is going so that if you don't get a follow up message to go to the last phase it doesn't keep running forever.
