### ISSUE TITLE
Determine how to capture participant's age

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#180]
Switch from the "x-y" groups to: ['Kid', 'Pre-Teen', 'Teen', 'Adult', 'Retired'];

**Comment by bryankennedy** [comment]
I'm making these changes for the event.

However, I'd like for us to talk these through a bit more at some point, so let's keep this open for more discussion. From one perspective, just asking a person for their specific year age is the best. But, I understand that this might not be desirable to share for many people.

Descriptive groups like these might be a bit more approachable for people. However, that are imperfect in their exclusivity. I think 12 year-olds would select `kid` and some 45 year-olds who would select retired...cause they are.

I totally understand the motivation, I just think we need to

**Comment by bherr2** [comment]
Yeah, understood. Its not ideal. After this we should work on a more concrete roadmap for finishing Phase 1 and planning what Phase 2 looks like.

**Comment by bryankennedy** [comment]
@bherr2, do you think this should stay in Phase 1. We might want to call the age-groups good for Phase 1 and then do some further work in Phase 2 to improve the UX and data storage of the runner's age.

**Comment by bherr2** [comment]
I think it should. I'd like to revise/refine the categories for Phase 1.

**Comment by bryankennedy** [comment]
Sounds good. I'm going to reach out to our research and evaluation department to ask them how they ask for this on demographic surveys. It would also be good to get Joe's feedback on how they might want to ask about this at COSI as well.

**Comment by bryankennedy** [comment]
Copying Joe's response here for reference:

> Here’s what COVES asks along with the explanation of why and how it’s analyzed.  Before you read it, let me say that I think this may be overkill for what we’re wanting (too many categories for youth and scale data for adult age):
>> Q20 Please tell us about yourself. What is your age?
>> Though we will cluster the answers for our analysis, we are leaving the question completely open to allow for as much digging in as you and your team would like to do! By getting actual ages, you will be able to break down the data in whatever way is best for your organization.
>
> SO, what we usually ask outside of this, is more aligned with the age/stage categories for both youth and adults.  We tend to lump all pre-kindergarten and kindergarten-aged youth into a “6 and under” unless there is something specific we’re looking for in ECE.
>
> So it’s often along the lines of 6 and under; 7-11 (or thereabouts depending on the developmental or relational aspect being measured); 14-17; 18-21; 21-35; 36-50, 51-65, 65+
>
> Those aren’t too many categories and we can make some developmental and/or life stage assumptions.  We often use a matric and ask for each age # Adult Males; #Adult Females; #Adult Non-binary; #boys; #girls; #non-binary.  Gibes us a quick count.
>
> Does this work?  I’ve included Elaine and Justin on this so they align the internal discussions we’ve had about data we’re collecting and share more accurately what we were thinking.  (I’m going more generic)

**Comment by scimap** [comment]
Age groups: 
0-6
7-13
14-17
18-21
21-35
36-50
51-65
65+

**Comment by katyb** [comment]
21 2x?
8 groups are a lot. Use color value and hue to distinguish?
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics, Computing, and Engineering, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166

**Comment by bryankennedy** [comment]
The age picker is working with the agreed upon groups. We'll continue to make some refinements as user testing begins, but I'm going to move this one to done. Refinements can be spelled out in more specific issues.
