### ISSUE TITLE
End-line sensor doesn't always pick up a runner

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#186]
When running fast, the end-line sensor doesn't always pick up that the runner has crossed. Currently we're telling people to slow down, but we need a more robust solution.

**Comment by bryankennedy** [comment]
I will talk with our fabrication team to see if there's anything that can be done with the existing sensor to address this.

If not, then we may need to switch to a different sensor approach with an emitter and a reflector, which will require a bit more of a furniture setup.

We'll plan to work on this with the goal of getting a more robust sensor setup for the COSI install.

**Comment by bryankennedy** [comment]
We have instructions on how to update the sensors. This should allow you to adjust the sensitivity to fix the problem.

I'd like to share this documentation as a markdown document within the repo, so that all technical documentation for the system lives within this repo. I'll get that committed and then you can give us feedback on how it works for you.

**Comment by bryankennedy** [comment]
@heidgera could you add your electronics documentation for this fix as a markdown document in the [documentation](https://github.com/cns-iu/xmacroscope/tree/master/documentation) folder?

To do this please create a new branch off develop and then we can review changes there. Thanks!

**Comment by bryankennedy** [comment]
This is a priority for Phase 1.

**Comment by heidgera** [comment]
Okay, documentation, schematic and program are in the branch 'reprogram-sensors'. Let me know if I should make organizational changes, or if anything doesn't make sense.

**Comment by bryankennedy** [comment]
Aaron, I made a few changes to that document and moved the sensor code to here.

Could you:

- [ ] Add a comment within the .ino code that details the value that controls the sample rate that will fix the sensor sensitivity?
- [ ] Update the documentation to reference that line so that other will know how to adjust that value?

**Comment by heidgera** [comment]
Okay, great. Your layout of the files makes more sense. I added the code comments, and amended the documentation.

**Comment by bryankennedy** [comment]
Nice, this makes more sense to me. Thanks for adding in that detail.

@bherr2 I assigned this back to you. Can someone on your team test out the process that Aaron has outlined in the documentation and let us know if it fixes the run speed sensing?

**Comment by bryankennedy** [comment]
@bherr2 and @scimap let us know if you're not able to purchase the FTDI cable that we called out in the [documentation](https://github.com/cns-iu/xmacroscope/blob/reprogram-sensor/documentation/sensorDetails.md#beambreak-reprogramming-instructions).

I listed a product at Sparkfun, but you mentioned B&H is a prefered vendor. I don't see anything comparable there right off the bat. Amazon, does have some options, but you said that that doesn't work.

If you need us to purchase and ship to you, let me know.

**Comment by scimap** [comment]
If you can ship it to us that would be great. Thanks.

**Comment by bryankennedy** [comment]
FYI, it actually looks like the cable will be there by the end of the day Wed:
https://d.pr/i/FKiZ9U

**Comment by bherr2** [comment]
@KalaRaja I'm assigning this task to you. The documentation for reprogramming the Sensor is here: [Documentation](https://github.com/cns-iu/xmacroscope/blob/reprogram-sensor/documentation/sensorDetails.md#beambreak-reprogramming-instructions). Come to my office when you get a chance and I'll get you the hardware.

**Comment by bherr2** [comment]
We ran the exhibit yesterday at en event and it looks like the changes in sensor sensitivity did the trick!
