### ISSUE TITLE
Add timeout/reset message and subscription for MAV timer reset

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#222]
With the removal of the opponent state we no longer have a message that helps the MAV reset its timer. SMM will work on a new message state that lets the MAV system know when the system has completed the timeout phase and the signup screen has switched back to the signup form.

**Comment by bryankennedy** [comment]
@bherr2 and I just talked this through on Slack. There are a few specific states that we'll create:

1. `run-signup` This is triggered when the signup screen is loaded, before the visitor has entered their data. The message for this state will only send time and type.
2. `run-pressed` This is triggered when the visitor has entered their data correctly and has pressed the RUN button. The message includes the time, type, run, and person.
3. `run-initiated` This is triggered when the pre run timeout ends and the timer is actually started. The audio clip plays "GO," and the visitor starts running towards the finish line. The message includes the time, type, run, and person.
4. `run-completed` This is triggered when the visitor crossed the finish line sensor. The message includes, time, type, run, and person.

After the post run timeout, the signup screen is loaded again, triggering number 1 message `run-signup` again.

**Comment by bryankennedy** [comment]
Implemented the first message, and it's called `signup-started`

Thinking about naming the next one `signup-finished`

I'd love to change `run-initiated` >> `run-started` and `run-completed` >> `run-finished` (for consistency) but @bherr2 you might be a little tired of me refactoring the naming. Let me know what you think.

**Comment by bherr2** [comment]
Fine with me

**Comment by bryankennedy** [comment]
I like that–single subscription. I think I was keeping the separate because I thought you wanted that. I'll merge and you can let me know if you're missing anything you need data wise.

**Comment by bherr2** [comment]
Let me know when the subscription is ready. My code is ready to pull it in.

**Comment by bryankennedy** [comment]
Each of these states now has a message under a single message subscription.

**Comment by bryankennedy** [comment]
New messages are implemented and coming through to MAV.
