### ISSUE TITLE
Develop simple v1 project website

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#224]
I'll send out a questionnaire to ensure I know the purpose of this site, from the perspective of all parties. Here's a start:
- A single place to send the general public to learn about the project
- List project partners and their general responsibilities
- List a high level technical overview of the Run xMacroscope system
- List research presentations and publications

@bherr2 @katyb @scimap - We discussed using xMacroscope.org as the URL for this site at one point. Is everyone OK with that?

We can either host the site on GitHub or SMM, depending on the technical setup.

@bherr2 what do you think about the website code being part of this single repo? Should it be in a separate repo?

**Comment by bherr2** [comment]
I like xMacroscope.org. I'd like to host it on GitHub, preferably in the same repo, but we need to figure out exactly how to do that.

I think this tutorial is close:
https://medium.com/employbl/launch-a-website-with-a-custom-url-using-github-pages-and-google-domains-3dd8d90cc33b

We can use Travis to build the demo sites and deploy along with the website (implemented however you like), so that the demos are just part of the website.

**Comment by katyb** [comment]
xMacroscope.org seems available. OK by me.
Please also add the video that Andreas made at Makevention to the site—until we have a better one from COSI or SMM setup.
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics, Computing, and Engineering, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166

**Comment by bryankennedy** [comment]
Domain is registered and setup is beginning - [xmacroscope.org](xmacroscope.org)

It doesn't resolve just yet, but I'll add a placeholder shortly and a v1 site will be setup by the end of this week.

**Comment by bryankennedy** [comment]
Very basic v1 website is up at xmacroscope.org.

Implemented:
- Basic project abstract description
- Outline of our work and the partner institutions
- Setup hosting and SSL certificate through the SMM load balancer ( this is something we'll need to figure out again differently when we switch to GitHub hosting ).
- Added Google Analytics (I'll work on sharing access to this out with the group at a later date.

I'm going to add a few more specific issues for various next steps.
