### ISSUE TITLE
DisplayShape component is called without required prop in RunnerIcon

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#226]
@azuldev1 could you look at this component?
https://github.com/cns-iu/xmacroscope/blob/723aa0b115669c8f8b26e7e2003c60f0864c893e/packages/client-run/src/Start/RunnerIcon.js#L15-L22

The DisplayShape component lists the `typeDisplay` prop as required but it's not listed here.

**Comment by bryankennedy** [comment]
I copied over the prop from another usage here:
```
            typeDisplay="viewDisplay"
```

It looks like you're just using this as a boolean in the actual component. Should we change the prop to be something like `controlled`? Change it to not required and set the default to not controlled.

**Comment by azuldev1** [comment]
I went ahead with your suggestion. Changed the prop name to controlled and made it type boolean. Made the default prop false.

**Comment by bryankennedy** [comment]
Thanks @azuldev1 . I did remove one more prop for type. It was leftover from your change but doesn't exist in the component.
