### ISSUE TITLE
client-run build fails because of pretty-ms module

### ISSUE THREAD

**Issue by bherr2** [cns-iu/xmacroscope#231]
When trying to build the client-run I get this error:
```
$ npm run build

> client-run@0.1.0 build /home/bherr/workspaces/aisl/xmacroscope/packages/client-run
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/pretty-ms/index.js:4

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-run@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client-run@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I believe its related to this: https://github.com/sindresorhus/pretty-ms/issues/31

This is important to fix asap as I am building the server to deploy here.

**Comment by bryankennedy** [comment]
pretty-ms is focused on the Node environment and not web JS. As a result it seems like it doesn't support transpiling within our ES6 project very well. We're only using it to convert milliseconds to human readable format for the Timer component. That component is only displaying the timer conditionally. In its current usage, we don't need to display it on any of the exhibit screens. So for now I'm just going to remove this module to address this issue.

**Comment by bryankennedy** [comment]
@bherr2 this commit fixes the issue for me. Close if you can confirm.

**Comment by bryankennedy** [comment]
Bruce confirmed this is working on Slack.
