### ISSUE TITLE
Website - Add institution icons

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#246]
In the partners section where we call out each institution involved with the project, we should add our logo images.

@scimap Do you have a good version of the CNS logo that I should use? Or would you rather I use the IU logo?

I'll reach out to Joe/Elaine (COSI) and Kylie (UC Irvine) via email about their logos.

**Comment by bherr2** [comment]
You can get the CNS logos from here: https://cns-iu.github.io/cns-styleguide/

**Comment by scimap** [comment]
Thanks, Bruce

**Comment by bryankennedy** [comment]
All partner logos are live. Please post any feedback if anyone wants to see their institution represented differently.

**Comment by bryankennedy** [comment]
I didn't get any feedback on this so I'm going to close.
