### ISSUE TITLE
Ensure drag and drop functionality is technically working on MAV at COSI

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#261]
Elaine has been conducting some testing at COSI with visitors. They are reporting some confusion about the MAV drag and drop operations. We should ensure that there aren't any technical issues related to the drag and drop axis values. I know that the touchscreen is registering touches, but it sounds like there might be a drag issue.

This task is distinct from evaluating the user interface associated with the drag and drop. In this issue, we're only trying to determine if it's technically working as designed.

**Comment by bherr2** [comment]
Commit 2c53a032d97fa90693a1fd9882f4b7a5c7a28eb9 adds proper touch support to the MAV screen. This will likely fix the issue, but needs to be tested on their machine. I tested it here on 3 different machines in both Chrome and Firefox, with and without touchscreen emulation.

**Comment by bherr2** [comment]
If deployment will take a little bit you can test with the staging demo site here:
https://xmacroscope.netlify.com/#/mav?showAppHeader=false

**Comment by bryankennedy** [comment]
After reviewing this with Elaine at COSI, we can say with certainty that the drag & drop functionality is working. Bruce added some visual feedback that helps demonstrate to the user how it works.
