### ISSUE TITLE
Angular compiler error related to new Typescript release

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#263]
On fresh installs the `npm run build` step is erroring out because of a new version of Typescript that was [released several days ago](https://github.com/Microsoft/TypeScript/releases).

When building the app now we get an error:
`The Angular Compiler requires Typescript >=3.1.1 and <3.3.0 but 3.3.1 was found instead.`

I was able to get the app to run by changing the [typescript version in `client-mav`](https://github.com/cns-iu/xmacroscope/blob/develop/packages/client-mav/package.json#L89) to `3.2.2` without the caret. But I wanted to see if that's how the CNS-IU team wants to address the issue.

This is [related to our effort to be a little more specific about package version numbers](url).

**Comment by bherr2** [comment]
Added bounded versioning for typescript that should take care of this `"typescript": ">=3.1.1 <3.3"` in package.json. Commit: 6e10c499787a38d99fa187c1c06aad139e5e07be
