### ISSUE TITLE
End line screen displays the wrong icon/color if the previous runner timed out

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#267]
Steps to reproduce:

1. On the start screen, signup and select a shape and color (e.g. yellow star).
2. Start the race but do not finish it. Yellow star will appear on the end line monitor during this unfinished race.
3. The end line screen and the start line will fully timeout and return to the sign up screen.
4. On the start screen, signup again, selecting a different color and shape (e.g. green square).
5. Start race. The end line screen will not show the shape and color you just selected, it will show the color and shape from step #1 (yellow star) in this case.

@bherr2 I'm still investigating whether this is an issue with the server sending out the wrong message, or if MAV is reacting incorrectly.

**Comment by bryankennedy** [comment]
I was able to confirm that the correct shapes are coming through in the GraphQL messages. When I view the backend screen on MAV I see the run-started message come through with the correct colors in each step. However, if a `run-started` message is followed by a `signup-started` message (the runner never crosses the finish line), then the end line screen won't respect the color/shape combo in the next `run-started` message. It will use the one from the previous state.

**Comment by bherr2** [comment]
This should be fixed in develop. You'll need to verify at COSI to be sure.

**Comment by bryankennedy** [comment]
This is fixed now. I tested it on my local dev setup and am seeing the correct color now.
I deployed the code to COSI, re-built the production app, and tested it there. It's working correctly there too. Thanks for the quick turnaround.
