### ISSUE TITLE
MAV data feed stops displaying new data after an undetermined period of time

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#268]
I'm not sure what's causing this issue right now, and I haven't been able to consistently reproduce it in a dev setup. But Elaine is reporting this issue does eventually come up in multiple testing sessions.

After a "few" runs the MAV screen stops displaying new data points in the table and graph. The start line kiosk is operating correctly, and the end line display continues showing the timer and icons.

If you press the "Reset" button in the bottom left of the MAV window, the data table and graph go blank. Once a new run is initiated the MAV station will start working again correctly.

One other thing I noticed: If you open a new Chrome window, pointed at the same URL, you can see new data coming in on that new window, while the old window in the background is not updating.

I can't immediately reproduce this error on my dev machine. It's possible that there is something related to:
 - Stele browsing the MAV
 - The network setup at COSI
 - The GraphQL server isn't sending out the correct messages

I'm not sure....

**Comment by bryankennedy** [comment]
I deployed this as COSI and am going to mark it as closed. I haven't been able to reproduce the issue. That being said, it took a little while to show up last time. If Elaine does some testing and notices anything, I'll reopen this.

**Comment by bryankennedy** [comment]
Elaine and I just spoke on the phone. There are still some issues with how the data is appearing in the MAV data table. We were able to confirm that when this is happening, that the **finish line sensor is properly completing the activity**. The MAV based finish line is stopping the timer, but the data table doesn't update.

Bruce what debug information would be helpful to work on this? I could set Stele to log the console messages to a file when MAV is running.

**Comment by bherr2** [comment]
Is there a way to open the console while its running and give me a call/zoom and we can look at it together like that? I need to inspect the state of the application to have a better idea of what's happening.

**Comment by bryankennedy** [comment]
I'm working on building that into Stele today.

But then I need to get Elaine to give me a call when the problem appears. I haven't been able to replicate it myself.

**Comment by bherr2** [comment]
Yeah, same here. Once we can reliably reproduce the problem, we will likely be able to fix it quickly.

**Comment by bryankennedy** [comment]
I've implemented a change to Stele, the kiosk browser system that displays the xMacroscope (https://github.com/scimusmn/stele). This change will make it possible for us to examine the console.log of the browser to see if I can give you any more details about what it causing the freeze in the MAV display.

I'll report back if/when I hear anything from Elaine.

**Comment by bryankennedy** [comment]
OK, I just got off the phone with Elaine. I can now reliably recreate the problem. I'm going to make some specific sub-issues to this so that I can detail out specific parts of the problem.

**Comment by bryankennedy** [comment]
This has been addressed in sub-issues. Will close once I get confirmation at COSI.
