### ISSUE TITLE
Eliminate the RESET button from the Make-a-Vis screen

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#271]
On the Make a Viz screen, the RESET button clears all data from the data table. Once this is done, there is no way to get it back. If you restart the browser past data points do not show up again. They are displayed in the graph, but only new data points will be displayed in the data table.

Elaine reports, and I agree, that this is very confusing. Their study relies upon this data table being populated with past data, and I think this is part of the design that Katy wanted. How hard would it be to eliminate this button? At COSI, they've put tape over this portion of the touchscreen to prevent visitors from touching it.

**Comment by bherr2** [comment]
Reset button should be just refreshing the screen (it's literally just doing a window.location.reload()) to set all the mappings back to their defaults. It should then be pulling in the last 50 runs right at the start.

**Comment by bryankennedy** [comment]
That's useful to know.

> It should then be pulling in the last 50 runs right at the start.
It is definitely not doing that.

I'll investigate as to whether my runs query is possibly not publishing new data correctly. 

That being said, what visitor experience utility does this button serve? We should address any underlying technical issue that causes a reload to create this problem, but why do you want to give the visitor a reload this page button?

**Comment by bryankennedy** [comment]
On my local machine I can replicate the issue that I think we're seeing with the `RESET` button.

If I navigate directly to `http://localhost:4000/mav/#/mav?showAppHeader=false` no data is displayed in the MAV screen. Nothing appears on the graph or the data table.
Screenshot: https://d.pr/i/hWcVIh

If I visit the base MAV path (`http://localhost:4000/mav`) I get redirected to `http://localhost:4000/mav/#/home`, and then click the `Make A Vis` tab, the data table and graph are displayed with data.
Screenshot: https://d.pr/i/y7FiLa

If I then hit `RESET` the data table and graph will go blank again.

Could this be related to how Express is serving the page interacting with the Angular hash routing?

**Comment by bherr2** [comment]
The core issue here was the query at the beginning to get the last 50 runs was happening too soon and never populating. Now, when reset is pressed it should return everything to the original settings and show the last 50 runs.

**Comment by bryankennedy** [comment]
Bruce addressed this in c24d064 and 4e993bc. Those fixes have been deployed to the kiosk. The data stream is working better now.

Will move to QA and close if Anna confirms it's working as expected.
