### ISSUE TITLE
Data table doesn't populate new points while a individual data point is selected

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#272]
Steps to reproduce:

1. Start up the xMacroscope exhibit and generate a few runs by entering data on the start screen and completing some runs. You should now see a few runs on the Make-a-Vis data table.
2. At the Make-a-Vis screen touch one of the runs in the data table. This will highlight the point in the graph. The data row will also be highlighted.
3. Go back to the start screen, fill it out, and complete a race.

What happens:
You'll notice your shape appears correctly on the end line timer while you are walking. However, your new data point will not appear in the data table on the Make a Vis screen. You can do more walks from the start screen and the end line timer will continue to show the correct shape. However, no new data points will show up on the Make a Vis data table.

If you then go to the Make-a-Vis screen and click `RESTART` the data table will populate with the runs that you've done since you selected a point in step 2.

What should happen:
The data table should continue to update with new runs even when you have a point selected. This is proving quite confusing to visitors and even the people running the data studies.

**Comment by bherr2** [comment]
The stopping of runs while the user has a runner selected was a feature, not a bug. If its confusing, let's talk about it as a design issue.

**Comment by bherr2** [comment]
The RESTART button is now removed. Runs will stream in regardless of if any row is selected.

**Comment by bryankennedy** [comment]
Built the new software and deployed it to the kiosk. Works much better now. Thanks! I'll move to QA and close if Anna confirms it's working as expected.
