### ISSUE TITLE
Update users

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#276]
@bherr2 could you update a few SMM staff in the xMacroscope repo?

- Remove Manuel - azuldev1 
- Remove Aaron - heidgera
- Add Caly McMorrow - calym
- Add Brandon Kipp - brandonwkipp
- Add Trygve Nordberg - tnordberg

**Comment by bherr2** [comment]
I made you an admin so that you can do whatever you need.

**Comment by bryankennedy** [comment]
I added the users I needed as collaborators. Bruce, I didn't remove Manuel and Aaron, since they were not listed as collaborators on this repo. I think they're just in a team in the CNS group. I'll leave you to clean that up as you want/need. Thanks.

**Comment by bherr2** [comment]
Ok, thanks. They've been removed.
