### ISSUE TITLE
Decorative arrow addition & section padding/spacing improvements

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/xmacroscope#341]
# xMacroscope UI updates after stakeholder review:

Modifications have been made to the design file:
- Ideally, the header sections on all pages are responsive. Currently, there is a large padding space above the text that feels a bit awkward. The website would appear more organized if the header text and the background image were always centered.
- Vertical padding has been reduced for all breakpoints.
- Spacing between text and page content has been reduced for all breakpoints.
- Arrows have been added to headers to let people know to continue to scroll. The arrows are entirely decorative.

## To Do:
- [x] Improve all headers across breakpoints. This will likely involve closer collaboration with me, so don't hesitate to reach out!
- [x] Add decorative arrows to the header sections.
- [x] Reduce vertical padding for sections for each breakpoint based on the design file.
- [x] Reduce spacing between text/page content for each breakpoint based on the design file.

## Resources:
- [xMacroscope Figma design file](https://www.figma.com/file/Nr7p41ABI8ZQ1q822PEzrw/xMacroscope?type=design&node-id=138-108&mode=design&t=rP2ZHKzoFOVHR4ms-4)

![image](https://github.com/cns-iu/xmacroscope/assets/97060856/6a76b476-2294-42a2-8a4f-c4f0d0f97368)

**Comment by libby-maier** [comment]
More details to follow on this before today's EOB.

**Comment by hsjoshi28** [comment]
Do you also need the arrow-downwards for Extra Small (XS) Breakpoint?

**Comment by libby-maier** [comment]
Yes, please! This has been added to the design file/prototype. Thank you @hsjoshi28!

**Comment by hsjoshi28** [comment]
Discussed with Libby, the preview is available here: https://64dbc7375541aa1a597b15b2--xmacroscope.netlify.app/media

To-Do: 
Figma changes: Font size for Home page, and research page 14 px. Code changes done.

**Comment by libby-maier** [comment]
Looks great!
