### ISSUE TITLE
xMacroscope design requests from 8.17.2023 review

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/xmacroscope#345]
# xMacroscope design requests from 8.17.2023 review

## Visualization improvement request:
The text is illegible and overlaps on the homepage Scatterplot Matrix image:
![image](https://github.com/cns-iu/xmacroscope/assets/97060856/0bf57618-b6ce-4bab-9e85-d3addcc4e58d)
### To Do:
- [x] Ensure all text is legible in this image.

## Font inspection request:
I'm still seeing kerning differences between the regular Inter font and the Inter font on the buttons. The letters on the buttons appear closer together or they appear in a different font weight than the specification.
![image](https://github.com/cns-iu/xmacroscope/assets/97060856/1649e7cc-9731-410b-ade1-2c845b7463e6)
![image](https://github.com/cns-iu/xmacroscope/assets/97060856/19a83fed-b7ce-434f-9c94-1bc8e1472a70)

### To Do:
- [x] Please inspect the button Inter font in Figma and the production site and confirm the fonts match exactly. If they do not match, please adjust the production site to match the specification.

**Comment by hsjoshi28** [comment]
The changes are done and preview is available at: https://64de4f804a6f982c31f4c6a6--xmacroscope.netlify.app/
