### ISSUE TITLE
zip code entry by user

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#37]
As an administrator, I would like users to enter their zip code so I can tie that to many other types of available data.

**Comment by bryankennedy** [comment]
Just tagging this so I can ask about it later. I'm not sure I understand the request here. We're adding the ability for visitors to add their zip code at the signup screen, but I'm unsure what the admin role here means.

**Comment by scimap** [comment]
This was a request for users to enter their zip code - ignore the "as an administrator" part. It came from a discussion about whether to have visitors enter zip code or county or home town and what type of data is useful for geospatial analysis.
