### ISSUE TITLE
data drops off the display after 50 runners

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#41]
@scimap commented on [Fri Feb 23 2018](https://github.com/cns-iu/aisl/issues/71)

**Comment by bryankennedy** [comment]
We should make the 200 number a variable that we track per location within the settings database.

**Comment by bherr2** [comment]
Yeah, definitely. Also, I think we were going to go with 50 now.

**Comment by bryankennedy** [comment]
I'll make 50 the default in the settings seed and you can use that in the MAV when you're ready to implement it.

**Comment by bryankennedy** [comment]
The query for number of runs accepts an `n` value now. Do you need us to do anything to make this work? Just checking on the state of this issue.

**Comment by bryankennedy** [comment]
@bherr2 is this fixed in #151 ?
