### ISSUE TITLE
add state map of OH with counties

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#68]
As a COSI visitor, I want to see a geomap of Ohio with variables by county, to better match the scale of the data, since most visitors will be from Ohio.

**Comment by bherr2** [comment]
I realize most of the backend piece is working with this, but until it can be shown in XMacroscope, it is not done.

**Comment by bherr2** [comment]
Can the stroke of the state be modified? its much thicker than country or world?

**Comment by bherr2** [comment]
Also, pulsing style doesn't match scatterplot's pulsing. The 'pulse' should be a yellowish color.
