### ISSUE TITLE
add state map of MN with counties

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#69]
As an SMM visitor, I want to see a geomap of Minnesota with variables by county, to better match the scale of the data, since most visitors will be from MN.

**Comment by bryankennedy** [comment]
We have several shapefiles that can be modified for this purpose when you get there. Let us know if we can help.

**Comment by bherr2** [comment]
This is done. We use the configuration settings from the server to determine what state to show by default for each instance.
