### ISSUE TITLE
Create initial start line screen

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#70]
As a user, I need a data entry screen, so that I can input data that will be included in my persona.
Minimum requirements: ability to select shape and color to represent the visitor in the MAV, the ability to enter height, and the ability to enter zip code.

**Comment by bryankennedy** [comment]
In our first pass getting the database connection working, we will be randomly generating these values for display in Make a Viz. After that we'll build in the form based system for creating these values manually.

**Comment by bryankennedy** [comment]
OK, the "initial" (not-pretty) startup screen is functioning in the `feature-smm-signup` branch. I'll mark this off and spell out next steps in some other issues.
