### ISSUE TITLE
Add location to the env settings to that MAV can set a default geomap location and zoom level

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#76]
As an xM administrator, I want to select a default location and zoom level for the geomap, so that it reflects where my visitors are from.

**Comment by bryankennedy** [comment]
SMM should add this to the settings file. Right now we have latitude and longitude as setting variables, but we might want to add state and city. @scimap and @bherr2 which do you think would be more valuable? Or does lat,long suffice?

**Comment by bherr2** [comment]
I think state level would be the furthest to go down to. If we have state we can key into a GeoJSON file and just extract the state + their counties.

**Comment by bryankennedy** [comment]
I added a field to the settings for the two letter usState identifier.
